# Generated by Django 4.2.6 on 2023-11-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(max_length=256)),
                ('body', models.TextField(blank=True)),
                ('author', models.CharField(max_length=256)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
